### ISSUE TITLE
Its colonzor48

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#10]
Hey guys you may remember me. I'm fine. Dont worry. And i'm sorry for being an obnoxious piece of crap. I've become alot more chill. If anyone wants to contact me about anything feel free to contact me on steam. as i dont use discord anymore. And im sorry for being toxic.(before you ask no i am not interasted in scc anymore. I have moved on to other things. Just wanted to tell everyone that i am okay and i am sorry for before) Please spread the word to other members of the old discord server if u are still in contact with them.

Peace out.

**Comment by Colonizor48** [comment]
Good luck with this project however. You are all doing better then i ever could. Albiet thats not saying much because i barely know how to code.

**Comment by Colonizor48** [comment]
Holy crap playing this remaster brings back alot of nostalgia and its only been 2 yrs.

**Comment by Colonizor48** [comment]
Actually. I would help. But i dont use discord anymore so i have no way of contacting anyone. Reguardless i will contribute whenever i can. I have no idea how to use c# or do art. So i guess ill just try to contribute ideas/shellcore designs?

**Comment by Colonizor48** [comment]
Anyway pnce you get around to it. I would love to help with ep3 story and idea wise. Idk how im going to do that. But google docs will probably be fine.

**Comment by rudderbucky** [comment]
Hey, I'm not sure you can join the discord, but that would probably be where we are going to work on the story.
