### ISSUE TITLE
A wiki would be nice

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#119]
A wiki of some sort would be nice, wether in game or on a seperate site, to view things like which cores have which parts.

**Comment by BaegEhl** [comment]
> A wiki of some sort would be nice, wether in game or on a seperate site, to view things like which cores have which parts.

The part index shows you where you can find any part in a world

**Comment by Colonizor48** [comment]
> 
> 
> > A wiki of some sort would be nice, wether in game or on a seperate site, to view things like which cores have which parts.
> 
> The part index shows you where you can find any part in a world

oh yeah. Still a wiki would be nice but this lowers its priority alot.
