### ISSUE TITLE
Mission loop in haven 3

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#120]
If you are going to the battlezone epsilon mission adn speak to the uninected scout in 140-920 it will send you back tot he mission where you clear delta

**Comment by rudderbucky** [comment]
Are you able to reproduce this?

**Comment by Colonizor48** [comment]
most likely yes. Is there a way to skip missions? Thats would make this less tedious.

**Comment by rudderbucky** [comment]
Please elaborate a bit more. We are unable to reproduce this issue

**Comment by Colonizor48** [comment]
In trying to make a save where the issue could be easly reproduced i found another issue that should be able to be easly reproduced.  A softlock when talking to sukrat after saving. Ill make that a seperate issue.

**Comment by Colonizor48** [comment]
I dont seem able to reproduce THIS issue in particular. I would close it for now but ill leave that up to you. Maybe uring the mission where you talk to the 3 scouts i did somthing wierd where it didnt register i had talked to him but did have me move on to the next shellcore? Maybe i closed the dialouge box instead of responding. I dont know i dont have time to test that right now.

**Comment by rudderbucky** [comment]
Would appreciate it if you could keep trying to get it to happen again.

**Comment by Colonizor48** [comment]
I will but not rn.
