### ISSUE TITLE
Random spawns should be tellegraphed with a slight delay

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#123]
Title. So i dont randomly die due to a core appearing out of thin air.

**Comment by rudderbucky** [comment]
What

**Comment by Colonizor48** [comment]
> 
> 
> What

I mean instead of just spawning randomly out of thin air enemy shellcores should appear after a few seconds with an animation beforehand. That way you can avoid them if you are low on health

**Comment by rudderbucky** [comment]
I dunno, lots of games allow random things to hurt/kill players. Especially since this was how the original games dealt with it, I see no issue here.

**Comment by Colonizor48** [comment]
> 
> 
> I dunno, lots of games allow random things to hurt/kill players. Especially since this was how the original games dealt with it, I see no issue here.

The origional games didnt have a party system. The point of a remake is to improve the game.
