### ISSUE TITLE
The worst mission in the game.

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#124]
The carrier conondrum mission needs to be reworked. Its basicly an escort mission(escorting siege turret) but your escort dies instantly due to a heavy drone without any tellegraphing. If you just try to rush head on you die due to your weapons targeting drones instead of the carrier. Making the outposts closser to the carrier would go a long way but wouldnt be enough. Also while doing the mission you risk going into siegezone novus by accident menaing you have to restart. Also make htier be less turrets and no siege turrets. These are just my suggestions you can fix it another way, regardless Please fix it.

**Comment by Colonizor48** [comment]
Legit it is easer to rush the carriers in siegezone novus where your not supposed to kill them then to kill the initial one the intended way.

**Comment by Colonizor48** [comment]
Seigezone novus also seems to be waaaay too hard for its own good. Unless this entire mission chain is meant to be endgame somehow. Not enough resources to build a defense fast enough.

**Comment by FoeFear** [comment]
I'll look into the carrier conundrum mission to see if i could alter some of those problems

**Comment by FoeFear** [comment]
So I have fixed some of those problems. Hopefully they would be in the next release.

**Comment by Colonizor48** [comment]
Thank you so much.
