### ISSUE TITLE
Softlock after mission where you kill the battlecore.

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#128]
Steps to reproduce,
Step 1. Do the mission where you kill the battlecore
Step 2. Once you do the mission save the game after you talk to the command center and sukrat does the cutscene where they upgrade their shell.
Step 3. Reload the game.
Step 4. After the cut scene is done talk to sukrat again and push the button to continue. If you exit the dialog box with the x button it wont work. It will not work if you are within ~300 pixels(rough approximation and probably completl wrong) of where you are when the cutscene normaly starts.
Step 5. If you have done this right it should re initiate the cutscene with sukrat
step 6. Congratulations, you soft locked yourself(but this can be fixed by just saving and quitting i think)

**Comment by Colonizor48** [comment]
Save for ease of reproduction. Just go streight to another sector and do the steps form step 5.
[EP1 Epsilon Reproduction Save - Backup 5.zip](https://github.com/rudderbucky/shellcore/files/7148908/EP1.Epsilon.Reproduction.Save.-.Backup.5.zip)

**Comment by rudderbucky** [comment]
Looks like the problem happens because you can use the party wheel during the cutscene, that should be fixed in the next hotfix.

**Comment by Colonizor48** [comment]
> 
> 
> Looks like the problem happens because you can use the party wheel during the cutscene, that should be fixed in the next hotfix.

Still shouldn't be possible to trigger the cut scene outside of haven 3. Especially because the cut scene was already triggered at the start(see the save this happens on). That may or may not soft lock without the party wheel. Even if it doesn't depending on where this happens it can take a long time to Finnish being for all intensive purposes a soft lock. And if your in a battle zone or something basically causing the other side to win or you getting killed during a cut scene. Which might crash who knows.

**Comment by Colonizor48** [comment]
Yeah it appears to 100% softlock without the party wheel.

**Comment by Colonizor48** [comment]
Actually you dont even need to be enar the edge. This happens if you just talk to sukrat again.

**Comment by rudderbucky** [comment]
This should be fixed now. How were you able to die in a cutscene? Did you initiate it in a deadzone

**Comment by Colonizor48** [comment]
> 
> 
> This should be fixed now. How were you able to die in a cutscene? Did you initiate it in a deadzone

I forgot to turn godmode on and as a very weak core who used godmode to get that far i died due to normal cores.

**Comment by rudderbucky** [comment]
How did these cores attack you during a cutscene? I'm pretty sure combat is disabled during cutscenes.

**Comment by Colonizor48** [comment]
> 
> 
> How did these cores attack you during a cutscene? I'm pretty sure combat is disabled during cutscenes.

The cutscene was bugged. It like kinda started but didnt have the black bars around the screen. Like the game didnt trigger the start of a cutscene but triggered some flag in the middle of it. Possibly leading to the softlock.

**Comment by rudderbucky** [comment]
Got it. Should be fixed now
