### ISSUE TITLE
more flexibility with core upgraders/upgrades in the map builder[SUGGESTION]

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#129]
I was working on a hard mode mod for the flash version of scc ep2 back in 2017 or so. Before I got banned from the discord. It was in early pre alpha but i remember the following changes.

1. You started with a light/semi core instead of a normal core and had to upgrade in haven 2.
2. More and harder enemies
3. A new shop in the upgrade sector with t3 parts.(This was an intigration of another mod made by someone else)
4. I think you could upgrade to a deadzone core which origionaly wasnt in the flash ver.

I would make this myself. And depending on how good it is it could be added maybe. Could you make custom parameters for core upgrades so that you can specify allowed upgrades with that upgrader and/or make it take somthing other then reputation to ugprade? And the ability to add custom upgrade paths in general?(The light core doesnt upgrade to anything) Or add the ability to upgrade core via cut scene so i could make it cost credits for just this one time? This would be very useful for custom map makers.

**Comment by rudderbucky** [comment]
This would be in line with something I would be okay with having in the game but I don't really plan on adding this myself. Leaving it as a suggestion in the trello in case someone else wants to make a pr

**Comment by FoeFear** [comment]
I previously tried making a pr with the semi-core as part of the upgrade chain but there was a problem with the core light not changing when it was upgraded. I would try it again, but I don't want to make a pr with unfixed bugs.

**Comment by Colonizor48** [comment]
On Hard mode im experimenting with various tests for spawning grounds. Now the spawning grounds would resemble a battleground much more with tougher drones and a few actual shellcores. Sukrat's inital form would be made stronger to compensate. Also it has the infected capital music because it sounds lit. Also there are ground stations to prvent you from groung trough the deadzones. Later in the game there would be a mission to liberate the spawning grounds where it would turn into a battlezone. Hopfully there is a way to save the changes made to the sector over time. Also instead of being given a speed thrust 1 you would be given a beam 1 at the very start.

**Comment by Colonizor48** [comment]
> 
> 
> I previously tried making a pr with the semi-core as part of the upgrade chain but there was a problem with the core light not changing when it was upgraded. I would try it again, but I don't want to make a pr with unfixed bugs.

I dont know unity but if you could fix that that would be epic pog.
