### ISSUE TITLE
Create a repo for bleeding edge builds.(and actually respond to my issues please)

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#14]
This repository would have a link in this repo's readme.md file to link to another repository where in this repository it would automatically create a new bleeding edge release whenever a commit is made. Like how Mindustry does BE builds.

**Comment by Colonizor48** [comment]
Or if not this atleast add instructions on how to build the game.

**Comment by rudderbucky** [comment]
Building the game unfortunately requires downloading the unity client. I'm not sure if there's another way around that.
