### ISSUE TITLE
Bug in Haven 3 and 4 missions:

### ISSUE THREAD

**Issue by AkagiVoid** [rudderbucky/shellcore#151]
The bug happened in "Haven 3" right after you get contacted by the infection massive core BOSS.
After he leaves, I went back up to Haven 3 as the orange arrow told me to do on the map, and after turning in the task to "Haven 3" Mission Control it keeps saying I need to "Reclaim BattleZone Epsilon for us." which I already did.
I went and did it again but it keeps saying to go and reclaim it still. >w>

Another bug in "Green Capital Center" where U talk to the Green Boss Leader and he sends you to "Haven 4".
But after U go there the leader in "Haven 4" haves nothing for U to do and UR just stuck there. >:/

**Comment by rudderbucky** [comment]
Please send me a save on Discord affected by this bug

**Comment by rudderbucky** [comment]
Cannot reproduce without a save file

**Comment by AkagiVoid** [comment]
Well, for one I do not support Discord anymore because of the spam bots. >w>
(Did do 2Step, keeps forgetting the password to login to it 2 get the access code for the discord).

And two, the bug only happens when U use cheats like "Immortality" in the console commands (used it 2 speed run to get to haven capital where I left off last time I played dis game). >w>

The funniest thing is dat it works normally when I reset my stats to normal by going 2 shipyard 2 reconstruct my ship which reset the immortality cheat dat was active, then go down and meet the infected leader boss for the first time. >w>

And third, U need 2 make it mar clear for the to user dat he needs to go to haven 2 and talk 2 weird looking ally dats sits just off the edge of the haven sector at the top center (took meh 4 ever 2 find which shellcore the mission was referring two after meeting the boss and going back 2 haven 3. >w>

And lastly, The haven 4 is still being developed or is dat where U end and Ur just left to play with Ur own devices?

**Comment by FoeFear** [comment]
> And third, U need 2 make it mar clear for the to user dat he needs to go to haven 2 and talk 2 weird looking ally dats sits just off the edge of the haven sector at the top center (took meh 4 ever 2 find which shellcore the mission was referring two after meeting the boss and going back 2 haven 3...

That part is intentional. Players are meant to search for someone who could help them get to the capitol. 
 
> And lastly, The haven 4 is still being developed or is dat where U end and Ur just left to play with Ur own devices?

Haven 4 is no longer in development. After completing truthful revelations, the jump gate is where players end episode 2 just as the original flash game. Episode 3 is under development but at a slow pace. There is extra content hidden in the main world for those who are up for a challenge.
