### ISSUE TITLE
Literal Entire game skip.

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#17]
Okay so you can kinda get to the capital within a few minutes of starting a new game by doing the following.

1. Go through danger zone 0-500 to battlezone delta. If you keep moving and dont stop you will make it.
2. Go to haven 3 and fix your core
3. get to the capital by going the normal way but travling along deadzone borders and going between the deadzone and normal sector over and over while moving forward.
4. Get to the capital in less then 4 minutes of gameplay.
This is kinda gamebreaking pls fix.
If you need a video of my route tell me and i will try to get one.

**Comment by Colonizor48** [comment]
My suggested fix would to just be add a metric craptone of deadzone cores to danger zone 0-500

**Comment by rudderbucky** [comment]
It's not really a game skip since you still need to do the initial missions but I see what you mean, I'll look into it.
