### ISSUE TITLE
Make turrets stronger the later you are in the game.

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#178]
Battlezone theta feels impossible because the enemy can just destroy your turrets extremely easily. As later in the game should become stronger to compensate for shell cores becoming stronger.

**Comment by FoeFear** [comment]
They already are. If you are playing the old version, they don't have it

**Comment by Colonizor48** [comment]
It still kind of feels like you can just rush down turrets. But that could just be me over leveling to an absurd extent.
