### ISSUE TITLE
Add the ability to give tanks commands

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#180]
Basically, when you double click a tank, you would be able to set it to offense mode or defense mode. In offense mode they would be primarily concerned with capturing enemy stuff, in defense mode they would be primaraly conscerned with defeating other tanks. This way tanks don't sacrifice themselves in siege zones

**Comment by FoeFear** [comment]
That wouldn't make it stay true to the original. I know the ai hasn't been implemented to move tanks from one platform to another, and it has been suggested (a couple of times at least). But giving the idea to command tanks feels like it would overcomplicate things.
