### ISSUE TITLE
A bug that makes it impossible to progress i think.

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#181]
I think some important event is supposed to happen upon enterning sector 1440-6760 during the aprt of the game where you have to escort the archatech. But it just gives an error.
![Screenshot (412)](https://github.com/rudderbucky/shellcore/assets/43299519/1568c677-e0d5-4f02-a161-d33f6b00b100)
[Player-prev.log](https://github.com/rudderbucky/shellcore/files/11713741/Player-prev.log)

**Comment by Colonizor48** [comment]
[Player.log](https://github.com/rudderbucky/shellcore/files/11713743/Player.log)

**Comment by FoeFear** [comment]
Yeah, it's a known bug. The next release would most likely fix it.

**Comment by Colonizor48** [comment]
> Yeah, it's a known bug. The next release would most likely fix it.

Is there a way to progress in the meantime?

**Comment by Colonizor48** [comment]
> Nope. There's a command, but it will make it worse. So, I would suggest you wait until another release comes out.

Is the bug one that could be fixed in the map editor?

**Comment by FoeFear** [comment]
If you want to get the latest release, you'll have to go to itch.io. Anything minor will be published there. https://rudderbucky.itch.io/shellcore/devlog/547959/201-beta-released
