### ISSUE TITLE
Multiplayer support

### ISSUE THREAD

**Issue by AkagiVoid** [rudderbucky/shellcore#191]
Tag dis as [ Idea ], and [ question ] pls. >w<
Will Shellcore command get multiplayer support like " [diep.io](https://diep.io/) " or something similar? :3

I think it would be cool if the player can host their own session for others to join in like a co-op of sorts. :P
Also I said similar not identical to diep game, so non of you have to actually fool around with servers as the player's host computer acts as the client as server at the same time taking out the costs 2 maintain a server. ^w^
So its like a Win n Win for both parties involved. :3

**Comment by FoeFear** [comment]
Try playing the game before making this post. It already exists.

**Comment by rudderbucky** [comment]
@AkagiVoid Multiplayer Skirmish is functional. Please join the Discord if you are interested in playing multiplayer.
