### ISSUE TITLE
[bug] Dialog windows heigher than screen height?

### ISSUE THREAD

**Issue by sommmen** [rudderbucky/shellcore#192]
Hello,

I'm just now trying out the game, it seems pop-up windows are higher than they should be:

![image](https://github.com/rudderbucky/shellcore/assets/8641495/4fe54767-6172-4557-b3cc-642a5d3858c5)
![image](https://github.com/rudderbucky/shellcore/assets/8641495/eb60ba79-f54f-446e-aaca-c2e32b5c43f9)
![image](https://github.com/rudderbucky/shellcore/assets/8641495/d0b971f7-47f1-4007-bc37-4d4f63eae83d)

Could this be due to my 3840x1080 screen? 

There seem to be no scroll bars but i can drag the windows of the shell configurator around so i can see everything,
But this seems not possible with the missions dialog.

**Comment by sommmen** [comment]
It seems scaling is based on the width not the height, and thus it gets messed up for large screens?

![2023-10-15_12-44-09](https://github.com/rudderbucky/shellcore/assets/8641495/a17d624a-e2c6-4132-b3ed-eb0a07249c2d)

**Comment by rudderbucky** [comment]
Are you able to play in windowed mode? The game isn't designed for ultrawide displays.

**Comment by sommmen** [comment]
> Are you able to play in windowed mode? The game isn't designed for ultrawide displays.

Its doable :)
