### ISSUE TITLE
Vigilant Crucaders.

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#20]
While poking around in the game files i found a map called vigilant crucaders in the map creator. I loaded it up and it seems to be a strange. Alternate universe type map with very diffrent sectors. What is this and how can i load into it in a normal game?

**Comment by Colonizor48** [comment]
It seems far to big to just be a test map. This is the zip. I swear i didnt make this. As I wouldnt even have an idea of how to give anyone here dialog. Also some of the sectors are so big they seem to actually lag the game. And there are 2 capitals. both named after real cities. and much closer to spawn.
[Vigilant Crusaders.zip](https://github.com/rudderbucky/shellcore/files/5797754/Vigilant.Crusaders.zip)

**Comment by Colonizor48** [comment]
I have intrest in loading this normaly because  the character creation screen with infinite parts kinda overrides what parts you actually have when testing. And you cant save when testing.

**Comment by Ormanus** [comment]
Vigilante Crusaders was made by Abnormalities. It's a custom map that, I
think, we were going to add to the game as featured community content.

You can play it by pressing F3 on the main menu and typing "load <map
folder name>" and starting a new save.

**Comment by Colonizor48** [comment]
Okay. For a second there i thought this was going to turn into a creppypasta as i couldn't find any references to it in the repo. But still this seems like a cool thingy and im going to give it a try. Also while were here can you guys work on documentation for the world creator? Because i want to see what i can do with it and if i can actually make anything good.

**Comment by Ormanus** [comment]
We (or rudderbucky mostly) are working on a big UI update for the world
creator. I think I also spotted "documentation" in our to-do list. :)

**Comment by Colonizor48** [comment]
allright thank you very much.
