### ISSUE TITLE
No way to make shellcores with light cores in the world creator

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#21]
I remember there being light cores in the original game. Which were used by some early game enemies and were weaker then small cores. And i remember i was working on a hard mode hack for episode 2 where you started with one and had to upgrade in haven 2. Amoung other changes making the game harder. Anyway there doesnt seem to make any shellcores with them in the editor. If they are in the game they should be in the editor.

**Comment by rudderbucky** [comment]
I don't have plans to add these in the game right now unfortunately.
