### ISSUE TITLE
Cant change sector color in world builder

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#22]
I cant change the sector default color. Trying to change it just makes it change to light blue.

**Comment by Colonizor48** [comment]
As in setting default sector settings doesnt do anything accept change backround particles.

**Comment by Colonizor48** [comment]
Also sorry for spaming this repo with issues i just want to give my suggestions and report bugs.

**Comment by rudderbucky** [comment]
This is a planned feature.
