### ISSUE TITLE
Can clear battlezones without killing all commanders. And this leads to them escaping battlezones.

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#29]

**Comment by rudderbucky** [comment]
Could you provide more info

**Comment by Colonizor48** [comment]
Okay so basicly. When you kill all of the carriers in a battlezone you
automaticly win. Without having to track down and kill any commanders. If
you leave the battlezone while the commander is alive but the carriees are
dead it glitches out and the commanders can leave the battlexone and follow
you. And even respawn when killed. The only way yo fix this is to reload
your save

**Comment by rudderbucky** [comment]
Which BattleZone is this happening in?

**Comment by Colonizor48** [comment]
All of them.

**Comment by Colonizor48** [comment]
Though i remember it most with battlezone epsilon.

**Comment by Colonizor48** [comment]
And battlezone gamma

**Comment by rudderbucky** [comment]
I tried gamma and it seems fine. Could you give me steps to reproduce the bug

**Comment by Colonizor48** [comment]
I will try later.
