### ISSUE TITLE
More suspific commit descriptions. Also please use the issue tracker for all bugs. regardless of how quickly they are fixed.

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#34]
Its just good practice. So i know what bugs were fixed and what was added exactly in a commit. If the changes are too big upload them in a paste bin or something. And use the issue tracker for all bugs so you could say for example "fixed 2012" Insteald of "bugfix"

**Comment by rudderbucky** [comment]
Didn't realize people actually read the commits. The  trello changelog tracks all fixed bugs so far, you can find it here - https://trello.com/b/drn4GWRl/shellcore-command
