### ISSUE TITLE
Game menu scaling with screen resolution

### ISSUE THREAD

**Issue by Bladewood** [rudderbucky/shellcore#4]
For reference, my monitor resolution is 1440x900.

When playing the game in an 800x600 window:
![image](https://user-images.githubusercontent.com/16506683/61582148-0048ef00-aaf5-11e9-8b0f-65e4b82f57dd.png)
1366x768 window:
![image](https://user-images.githubusercontent.com/16506683/61582134-dc85a900-aaf4-11e9-94ee-5770a1892622.png)
Often I use 800x600 because I want to do other things with my computer at the same time, but that makes it pretty hard to read the game.

**Comment by rudderbucky** [comment]
Removing resolution dependence on all UI elements is required in the future as well
