### ISSUE TITLE
Save state can be ruined if newborn dies during escort mission 

### ISSUE THREAD

**Issue by Admiral-Ackweed** [rudderbucky/shellcore#5]
Version: Alpha Release 3 1.0.1
This is happens very consistently for me if there are 2 or more enemies left in the spawn sector. (mini drones are strong?!)

Can be recreated if you re-enter the sector down the south end during the mission which respawns all the enemies, or flank the drones in the sector. The newborn AI seeks out enemies from a very long range and engages them instead of staying close to you so it can easily get itself killed.

Solutions
Respawn the newborn if it dies (Newborn death should probably fail the quest tbh)
Implement mission failure. (They could just mark the quest as done but the player misses out on any rewards. Original game has this feature too and it's useful for some quests like in EP2 where you chase the defector)
Improve the AI of ships you escort so that they remember to stay close to you instead of flying toward any enemy it sees and as a result killing itself.

**Comment by rudderbucky** [comment]
Mission failure is how this will be fixed, we just haven't implemented it yet.
