### ISSUE TITLE
This game needs anti aliasing.

### ISSUE THREAD

**Issue by Colonizor48** [rudderbucky/shellcore#54]
Please not FXAA or TAA though. This game can use MSAA or SSAA just fine.

**Comment by rudderbucky** [comment]
Maybe as an option, but I don't think anti aliasing should be on for all players without choice.

**Comment by Colonizor48** [comment]
Allright. I would recomend SSAA if you are going to do it as this is a 2d game and even potato gpus should be able to run SSAA fine.
