### ISSUE TITLE
Screen resolution is reset to smallest option in fullscreen and windowed after entering/exiting savegames

### ISSUE THREAD

**Issue by Admiral-Ackweed** [rudderbucky/shellcore#6]
Version: Alpha Release 3 1.01
Wondering if this has been fixed/updated since I saw someone in discord talking about using 800x600 windowed but my options are 1024x768, 1366x768, 1920x1080(pretty good for me on my 1600x900 screen) and 3840x2160.

The save changes button appears to not actually save resolution changes permanently whether I set them and then go into a savegame or set them in the save game and go back to the main menu. It does save misc and sound settings properly though.

**Comment by rudderbucky** [comment]
800x600 is not supported anymore, and it most likely won't be going forward. As for the resolution not saving, please give instructions on how to reproduce the issue, it seems to save correctly when simply changing it and restarting.

**Comment by Admiral-Ackweed** [comment]
Fiddled around with it more, only seems to happen on 1920x1080 and 3840x2160. Something is resetting the resolution back to the smallest option whether I am in windowed or fullscreen mode after entering or exiting saves, or restarting the game. My screen size is 1600x900 so maybe it happens because the affected options are bigger than that? 1920x1080 looks much nicer than 1366x768 though :(

**Comment by rudderbucky** [comment]
I think Unity doesn't like the fact that you are using a higher screen resolution than your monitor's maximum. I'll try to see if there's a way to circumvent this but this is kind of a low priority issue.

**Comment by Admiral-Ackweed** [comment]
> I'll try to see if there's a way to circumvent this

Is it feasible to add more resolutions? I thought 1600x900 was a common one. The aspect ratio is still the same as 1366x768 and 1920x1080 isn't it?

**Comment by rudderbucky** [comment]
That's a good idea actually. I'll add it in.
