### ISSUE TITLE
[Quest] Fetch parts from sector west of haven 1 does not care if you fetch any part, as long as you have entered the sector by the time you equip it in the shipyard.

### ISSUE THREAD

**Issue by Admiral-Ackweed** [rudderbucky/shellcore#7]
Version: Alpha  Release 3 1.0.1
Drop-rate also seems finicky, I think I'm getting parts from cores and drones at the same rate, which makes it easier to farm drones to get parts at the moment.

Solutions
I propose that at least 1 of the cores in the sector should be guaranteed to drop a part if it can. Due to probabilities at the moment it's possible to clear the sector twice and not get a part, or get 2 parts from the first enemy you kill. 
Track that the part came from that sector somehow, maybe by including data of which sector the part was spawned in.

**Comment by rudderbucky** [comment]
Drones will not drop parts in the future. In that case this issue is solved as it'd be infeasible to get a part from a faraway sector to complete the task. Part guarantees will likely be implemented as well. As for part tracking, it seems too complicated for such an issue.

**Comment by Admiral-Ackweed** [comment]
That's fair.
In the flash version I do recall a few cores in that east sector alongside the drones, which were the same type of cores as the ones in the west sector.
